package com.haisheng.framework.testng.CommonDataStructure;

import org.testng.annotations.DataProvider;

public class CommodityManaAccuracyRate {

    private static String outOfStock = "OUT_OF_STOCK";
    private static String wrongPlace = "WRONG_PLACE";
    private static String wrongPlaceAndOutOfStock = "WRONG_PLACE:OUT_OF_STOCK";


    @DataProvider(name = "ACCURACY_RATE")
    private static Object[][] testAccuracyRate() {
        //Dchng  Dtotal bindingStock  bindingTotal DwrongChng DwrongTotal, wrongAlarm  wrongStock
        //Pchng1 Ptotal1  {alarm1} stock1    Pchng2 Ptotal2  {alarm2} stock2
        //Pchng3 Ptotal3  {alarm3} stock3   Pchng4 Ptotal4  {alarm4} stock4
        //Pchng5 Ptotal5  {alarm5} stock5    Pchng6 Ptotal6  {alarm6} stock6
        Object[][] objects = {
                // 5对1错   六个商品单独拿
//                --------------------------------------1-6---------------------------------------------------------
                new Object[]{
                         100, 500, 5, 500,  50, 550, wrongPlace, 5,
                        -100, 450, wrongPlace,                   4, -100, 350, wrongPlace,              3,
                        -100, 250, wrongPlaceAndOutOfStock,      2, -100, 150, wrongPlaceAndOutOfStock, 1,
                        -100, 50,  wrongPlaceAndOutOfStock,      0, -50,  -3,  outOfStock,              0
                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100, 450, wrongPlace,                   4, -100, 350, wrongPlace,              3,
//                        -100, 250, wrongPlaceAndOutOfStock,      2, -100, 150, wrongPlaceAndOutOfStock, 1,
//                        -50, 100,  outOfStock,                   1, -100, -3,  outOfStock,              0
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100, 450, wrongPlace,                   4, -100, 350, wrongPlace,              3,
//                        -100, 250, wrongPlaceAndOutOfStock,      2, -50, 200,  outOfStock,              2,
//                        -100, 100, outOfStock,                   1, -100, -3,  outOfStock,              0
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100, 450, wrongPlace,                   4, -100, 350, wrongPlace,              3,
//                        -50, 300,  "",                           3, -100, 200, outOfStock,              2,
//                        -100, 100, outOfStock,                   1, -100, -3,  outOfStock,              0
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100, 450, wrongPlace,                   4, -50, 400,  "",                      4,
//                        -100, 300, "",                           3, -100, 200, outOfStock,              2,
//                        -100, 100, outOfStock,                   1, -100, -3,  outOfStock,              0
//                },
//
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -50, 500,  "",                           5, -100, 400, "",                      4,
//                        -100, 300, "",                           3, -100, 200, outOfStock,              2,
//                        -100, 100, outOfStock,                   1, -100, -3,  outOfStock,              0
//                },
//
//                // 5对1错   一起拿一对一错，其他四个正确的单独拿
////                ----------------------------------------------7-11--------------------------------------------
//
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -150, 400, "",                           4, -100, 300,  "",                     3,
//                        -100, 200, outOfStock,                   2, -100, 100, outOfStock,              1,
//                        -100, -3,  outOfStock,                   0,  0,   -3,  outOfStock,              0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100, 450, wrongPlace,                   4, -150, 300,  "",                     3,
//                        -100, 200, outOfStock,                   2, -100, 100, outOfStock,              1,
//                        -100, -3,  outOfStock,                   0,  0,   -3,  outOfStock,              0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100, 450, wrongPlace,                   4, -100, 350,  wrongPlace,             3,
//                        -150, 200, outOfStock,                   2, -100, 100, outOfStock,              1,
//                        -100, -3,  outOfStock,                   0,  0,   -3,  outOfStock,              0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100, 450, wrongPlace,                   4, -100, 350,  wrongPlace,             3,
//                        -100, 250, wrongPlaceAndOutOfStock,      2, -150, 100,  outOfStock,             1,
//                        -100, -3,  outOfStock,                   0,  0,   -3,  outOfStock,              0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100, 450, wrongPlace,                   4, -100, 350,  wrongPlace,             3,
//                        -100, 250, wrongPlaceAndOutOfStock,      2, -100, 150,  wrongPlaceAndOutOfStock,1,
//                        -150, -3,  outOfStock,                   0,  0,   -3,  outOfStock,              0,
//                },
//
//                // 5对1错   一起拿两个对的，其他3个正确的和一个错的单独拿
////                ---------------------------------------------12-15-------------------------------
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -200, 350, wrongPlace,                   3, -100, 250,  wrongPlaceAndOutOfStock,2,
//                        -100, 150, wrongPlaceAndOutOfStock,      1, -100, 50,   wrongPlaceAndOutOfStock,0,
//                        -50,  -3,  outOfStock,                   0,  0,   -3,  outOfStock,              0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -200, 350, wrongPlace,                   3, -100, 250,  wrongPlaceAndOutOfStock,2,
//                        -100, 150, wrongPlaceAndOutOfStock,      1, -50, 100,   outOfStock,             1,
//                        -100,  -3,  outOfStock,                  0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -200, 350, wrongPlace,                   3, -100, 250,  wrongPlaceAndOutOfStock,2,
//                        -50,  200, outOfStock,                   2, -100, 100,  outOfStock,             1,
//                        -100,  -3, outOfStock,                   0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -200, 350, wrongPlace,                   3, -50, 300,   "",                     3,
//                        -100,  200, outOfStock,                   2, -100, 100,  outOfStock,             1,
//                        -100,  -3, outOfStock,                   0,  0,   -3,   outOfStock,             0,
//                },
//
////                --------------------------------------16-20-----------------------------------------------------------------------------------------------
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -50,   500,   "",                        5, -200, 300,   "",                     3,
//                        -100,  200, outOfStock,                   2, -100, 100,  outOfStock,             1,
//                        -100,  -3, outOfStock,                   0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -50,   500,   "",                        5, -100, 400,   "",                     4,
//                        -200,  200, outOfStock,                  2, -100, 100,  outOfStock,             1,
//                        -100,  -3, outOfStock,                   0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -50,   500,   "",                        5, -100, 400,   "",                     4,
//                        -100,  300,   "",                        3, -200, 100,  outOfStock,             1,
//                        -100,  -3, outOfStock,                   0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -50,   500,   "",                        5, -100, 400,   "",                     4,
//                        -100,  300,   "",                        3, -100, 200,  outOfStock,             2,
//                        -200,  -3, outOfStock,                   0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                4, -50, 400,   "",                     4,
//                        -100,   300,   "",                        3, -100, 200,  outOfStock,             2,
//                        -200,  -3, outOfStock,                   0,  0,   -3,   outOfStock,             0,
//                },
//
////                --------------------------------------21-25-----------------------------------------------------------------------------------------------
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                4, -50, 400,   "",                     4,
//                        -100,   300,   "",                        3, -200, 100,  outOfStock,             1,
//                        -100,  -3, outOfStock,                   0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                4, -50, 400,   "",                     4,
//                        -200,   200,   outOfStock,                2, -100, 100,  outOfStock,             1,
//                        -100,  -3, outOfStock,                   0,  0,   -3,   outOfStock,              0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                4, -100, 350,   wrongPlace,             3,
//                        -50,    300,   "",                        3, -100, 200,  outOfStock,             2,
//                        -200,  -3, outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                4, -100, 350,   wrongPlace,             3,
//                        -50,    300,   "",                        3, -200, 100,  outOfStock,             1,
//                        -100,  -3, outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                4, -100, 350,   wrongPlace,             3,
//                        -100,   250,   wrongPlaceAndOutOfStock,   2, -50, 200,  outOfStock,               2,
//                        -200,  -3,     outOfStock,                0,  0,   -3,   outOfStock,             0,
//                },
//
//                //----------------26-30-------------------------------------------------------------------------------------------------------------
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                4, -100, 350,   wrongPlace,             3,
//                        -100,   250,   wrongPlaceAndOutOfStock,   2, -200, 50,    wrongPlaceAndOutOfStock,0,
//                        -50,  -3,      outOfStock,                0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                4, -100, 350,   wrongPlace,             3,
//                        -200,   150,   wrongPlaceAndOutOfStock,   1, -100, 50,    wrongPlaceAndOutOfStock,0,
//                        -50,  -3,      outOfStock,                0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                4, -100, 350,   wrongPlace,             3,
//                        -200,   150,   wrongPlaceAndOutOfStock,   1, -50, 100,    outOfStock,             1,
//                        -100,  -3,      outOfStock,                0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                4, -200, 250,   wrongPlaceAndOutOfStock,2,
//                        -100,   150,   wrongPlaceAndOutOfStock,   1, -100, 50,    wrongPlaceAndOutOfStock,0,
//                        -50,  -3,      outOfStock,                0,  0,   -3,   outOfStock,              0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                4, -200, 250,   wrongPlaceAndOutOfStock,2,
//                        -100,   150,   wrongPlaceAndOutOfStock,   1, -50, 100,    outOfStock,             1,
//                        -100,  -3,      outOfStock,               0,  0,   -3,   outOfStock,             0,
//                },
//
//                //----------------31-35-------------------------------------------------------------------------------------------------------------
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                4, -200, 250,   wrongPlaceAndOutOfStock,2,
//                        -50,    200,   outOfStock,                2, -100, 100,    outOfStock,            1,
//                        -100,  -3,      outOfStock,               0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -300,   250,   wrongPlaceAndOutOfStock,   2, -100, 150,   wrongPlaceAndOutOfStock,1,
//                        -100,   50,    wrongPlaceAndOutOfStock,    0, -50,  -3,    outOfStock,         0,
//                        0,  -3,      outOfStock,               0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -300,   250,   wrongPlaceAndOutOfStock,   2, -100, 150,   wrongPlaceAndOutOfStock,1,
//                        -50,   100,    outOfStock,                1, -100,  -3,    outOfStock,            0,
//                         0,  -3,      outOfStock,               0,  0,   -3,   outOfStock,             0,
//                },
//
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -300,   250,   wrongPlaceAndOutOfStock,   2, -50, 200,   outOfStock,               2,
//                        -100,   100,    outOfStock,               1, -100,  -3,    outOfStock,            0,
//                        0,  -3,      outOfStock,               0,  0,   -3,   outOfStock,             0,
//                },
//
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                   4, -300, 150,   wrongPlaceAndOutOfStock,1,
//                        -100,   50,    wrongPlaceAndOutOfStock,      0, -50,  -3,    outOfStock,             0,
//                        0,  -3,      outOfStock,                     0,  0,   -3,   outOfStock,             0,
//                },
//
////                ----------------36-40-------------------------------------------------------------------------------------------------------------
//
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                  4, -300, 150,   wrongPlaceAndOutOfStock,1,
//                        -50,   100,    outOfStock,                  1, -100,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                  4, -100, 350,   wrongPlace,             3,
//                        -50,   300,    "",                          3, -300,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                  4, -100, 350,   wrongPlace,             3,
//                        -300,   50,    wrongPlaceAndOutOfStock,     0, -50,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                  4, -50, 400,   "",                      4,
//                        -100,   300,    "",                         3, -300,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                  4, -50, 400,   "",                      4,
//                        -300,   100,    outOfStock,                 1, -100,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//
//                //                ----------------41-45-------------------------------------------------------------------------------------------------------------
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -50,   500,   "",                           5, -300, 200,   outOfStock,             2,
//                        -100,   100,    outOfStock,                 1, -100,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -50,   500,   "",                           5, -100, 400,   "",                    4,
//                        -300,   100,    outOfStock,                 1, -100,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -50,   500,   "",                           5, -100, 400,   "",                    4,
//                        -100,   300,    "",                         3, -300,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -250,   300,   "",                           3, -100, 200,   outOfStock,           2,
//                        -100,   100,    outOfStock,                  1, -300,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                   4, -250, 200,   outOfStock,           2,
//                        -100,   100,    outOfStock,                  1, -100,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//
////                ----------------46-50-------------------------------------------------------------------------------------------------------------
//
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                   4, -100, 350,   wrongPlace,            3,
//                        -250,   100,    outOfStock,                  1, -100,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                   4, -100, 350,   wrongPlace,             3,
//                        -100,   250,    wrongPlaceAndOutOfStock,     2, -250,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -400,   150,   wrongPlaceAndOutOfStock,      1, -100, 50,   wrongPlaceAndOutOfStock,0,
//                        -100,   -3,    outOfStock,                   0, 0,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -400,   150,   wrongPlaceAndOutOfStock,      1, -50, 100,   outOfStock,           1,
//                        -100,   -3,    outOfStock,                   0, 0,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                  4, -400, 50,   wrongPlaceAndOutOfStock,0,
//                        -50,   -3,    outOfStock,                   0, 0,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//
////                ----------------51-55-------------------------------------------------------------------------------------------------------------
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                  4, -50, 400,   "" ,                 4,
//                        -400,   -3,    outOfStock,                   0, 0,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -50,   500,    "",                           5, -100, 400,   "" ,                 4,
//                        -400,   -3,    outOfStock,                   0, 0,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -50,   500,    "",                            5, -400, 100,   outOfStock ,           1,
//                        -100,   -3,    outOfStock,                    0, 0,  -3,   outOfStock,             0,
//                        0,  -3,        outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -350,   200,   outOfStock,                  2, -100, 100,   outOfStock ,           1,
//                        -100,   -3,    outOfStock,                   0, 0,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                  4, -350, 100,   outOfStock ,           1,
//                        -100,   -3,    outOfStock,                   0, 0,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//
////                ----------------56-60-------------------------------------------------------------------------------------------------------------
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                  4, -100, 350,   wrongPlace ,           3,
//                        -350,   -3,    outOfStock,                   0, 0,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -500,   50,   wrongPlaceAndOutOfStock,       0, -50, -3,   outOfStock ,           0,
//                        0,   -3,    outOfStock,                   0, 0,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -50,   500,   "",                         5, -500, -3,   outOfStock ,           0,
//                        0,   -3,    outOfStock,                   0, 0,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -450,   100,   outOfStock,                1, -100, -3,   outOfStock ,           0,
//                        0,   -3,    outOfStock,                   0, 0,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -100,   450,   wrongPlace,                4, -450, -3,   outOfStock ,           0,
//                        0,   -3,    outOfStock,                   0, 0,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//
////                ----------------61-------------------------------------------------------------------------------------------------------------
//                new Object[]{100, 500, 5, 500,  50, 550, wrongPlace, 5,
//                        -550,   -3,   outOfStock,                0, 0, -3,   outOfStock ,           0,
//                        0,   -3,    outOfStock,                   0, 0,  -3,   outOfStock,             0,
//                        0,  -3,      outOfStock,                    0,  0,   -3,   outOfStock,             0,
//                },
//
////                正确商品4，错误商品1
////------------------------------------------1-5-五个商品都单独拿------------------------------------------------------------------------------------------------------------
//
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -50,   400,   "",                         4, -100, 300,   "",                    3,
//                        -100,   200,   outOfStock,                2, -100, 100,  outOfStock,             1,
//                        -100,  -3, outOfStock,                   0,  0,   -3,   outOfStock,              0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,               3, -50, 300,   "",                    3,
//                        -100,   200,   outOfStock,                2, -100, 100,  outOfStock,             1,
//                        -100,  -3, outOfStock,                   0,  0,   -3,   outOfStock,              0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,               3, -100, 250,   wrongPlaceAndOutOfStock,2,
//                        -50,   200,   outOfStock,                2, -100, 100,  outOfStock,             1,
//                        -100,  -3, outOfStock,                   0,  0,   -3,   outOfStock,              0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,               3, -100, 250,   wrongPlaceAndOutOfStock,2,
//                        -100,   150,   wrongPlaceAndOutOfStock,  1, -50, 100,  outOfStock,             1,
//                        -100,  -3, outOfStock,                   0,  0,   -3,   outOfStock,              0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,               3, -100, 250,   wrongPlaceAndOutOfStock,2,
//                        -100,   150,   wrongPlaceAndOutOfStock,  1, -100, 50,    wrongPlaceAndOutOfStock,0,
//                        -50,  -3, outOfStock,                    0,  0,   -3,   outOfStock,              0,
//                },
//
////        ------------------------------6-9- 1错1对一起拿，其他三个对的单独拿------------------------------------------------------------------------------------------------------------
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -150,   300,   "",                           3, -100, 200,   outOfStock,           2,
//                        -100,   100,   outOfStock,                   1, -100, -3,    outOfStock,           0,
//                        0,  -3, outOfStock,                          0,  0,   -3,   outOfStock,              0,
//                },
//
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,                   3, -150, 200,   outOfStock,    2,
//                        -100,   100,   outOfStock,                   1, -100, -3,    outOfStock,           0,
//                           0,    -3,   outOfStock,                   0,  0,   -3,   outOfStock,              0,
//                },
//
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,                   3, -100, 250,   wrongPlaceAndOutOfStock,2,
//                        -150,   100,   outOfStock,                   1, -100, -3,    outOfStock,           0,
//                           0,   -3,    outOfStock,                   0,  0,   -3,   outOfStock,              0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,                   3, -100, 250,   wrongPlaceAndOutOfStock,2,
//                        -100,   150,   wrongPlaceAndOutOfStock,      1, -150, -3,    outOfStock,           0,
//                        0,  -3, outOfStock,                   0,  0,   -3,   outOfStock,              0,
//                },
//
////   -------------------------10-21--两个对的一起拿，其他三个单独拿----------------------------------------------------------------------------------------------------------
//
////                ------------------------------------10-15------------------------------------------------------------
//
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -200,   250,   wrongPlaceAndOutOfStock,          2, -100, 150,   wrongPlaceAndOutOfStock,1,
//                        -100,   50,    wrongPlaceAndOutOfStock,          0, -50,  -3,    outOfStock,           0,
//                           0,   -3,    outOfStock,                       0,  0,   -3,    outOfStock,              0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -200,   250,   wrongPlaceAndOutOfStock,           2, -100, 150,   wrongPlaceAndOutOfStock,1,
//                        -50,   100,    outOfStock,                        1, -100, -3,    outOfStock,           0,
//                          0,    -3,    outOfStock,                        0,  0,   -3,   outOfStock,              0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -200,   250,   wrongPlaceAndOutOfStock,          2, -50, 200,   outOfStock,             2,
//                        -100,   100,   outOfStock,                        1, -100, -3,    outOfStock,           0,
//                        0,  -3, outOfStock,                   0,  0,   -3,   outOfStock,              0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,                   3, -200, 150,   wrongPlaceAndOutOfStock,   1,
//                        -100,   50,   wrongPlaceAndOutOfStock,       0, -50, -3,     outOfStock,           0,
//                        0,  -3, outOfStock,                   0,  0,   -3,   outOfStock,              0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,                   3, -200, 150,   wrongPlaceAndOutOfStock,   1,
//                        -50,    100,   outOfStock,                   1, -100, -3,    outOfStock,                0,
//                          0,     -3,   outOfStock,                   0,  0,   -3,   outOfStock,                 0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,                   3, -100, 250,   wrongPlaceAndOutOfStock, 2,
//                        -200,    50,   wrongPlaceAndOutOfStock,      0, -50, -3,    outOfStock,               0,
//                           0,    -3,   outOfStock,                   0,  0,   -3,   outOfStock,               0,
//                },
//
////     ----------------------------------16-21------------------------------------------------------------------------------------
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,                   3, -100, 250,   wrongPlaceAndOutOfStock,  2,
//                         -50,   200,   outOfStock,                   2, -200,  -3,   outOfStock,               0,
//                           0,    -3,   outOfStock,                   0,    0,  -3,   outOfStock,               0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,                   3, -50, 300,   "",             3,
//                        -200,   100,   outOfStock,                   1, -100, -3,    outOfStock,    0,
//                           0,    -3,   outOfStock,                   0,  0,   -3,   outOfStock,     0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,                   3, -50, 300,   "",             3,
//                        -100,   200,   outOfStock,                   2, -200, -3,    outOfStock,    0,
//                           0,    -3,   outOfStock,                   0,  0,   -3,    outOfStock,    0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -50,   400,     "",                          4, -100, 300,   "",             3,
//                        -100,   200,   outOfStock,                   2, -200, -3,    outOfStock,     0,
//                           0,    -3,   outOfStock,                   0,  0,   -3,    outOfStock,     0,
//                },
//
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -50,   400,    "",                           4, -100, 300,   "",             3,
//                        -200,  100,   outOfStock,                    1, -100, -3,    outOfStock,     0,
//                           0,  -3,    outOfStock,                    0,  0,   -3,    outOfStock,     0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -50,   400,   "",                            4, -200, 200,   outOfStock,     2,
//                        -100,   100,   outOfStock,                   1, -100, -3,    outOfStock,     0,
//                             0,  -3,   outOfStock,                   0,  0,   -3,    outOfStock,     0,
//                },
//
////                --------------------22-27- 三个对的一起拿，其他两个单独拿----------------------------------------------------------------------------------------------------------
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -300,   150,   wrongPlaceAndOutOfStock,      1, -100, 50,   wrongPlaceAndOutOfStock,0,
//                         -50,     0,   outOfStock,                   0,    0, -3,    outOfStock,            0,
//                           0,    -3,   outOfStock,                   0,    0, -3,    outOfStock,            0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -300,   150,   wrongPlaceAndOutOfStock,      1, -50, 100,    outOfStock,           1,
//                        -100,   -3,    outOfStock,                   0,   0,  -3,    outOfStock,           0,
//                           0,   -3,    outOfStock,                   0,   0,  -3,    outOfStock,           0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,                   3, -300, 50,   wrongPlaceAndOutOfStock,0,
//                         -50,    -3,   outOfStock,                   0,    0, -3,   outOfStock,             0,
//                           0,    -3,   outOfStock,                   0,    0, -3,   outOfStock,             0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -50,   400,   "",                            4, -300, 100,   outOfStock,            1,
//                        -100,   -3,   outOfStock,                    0,    0,  -3,   outOfStock,            0,
//                           0,   -3,   outOfStock,                    0,    0,  -3,   outOfStock,            0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,                   3, -50, 300,   "",                     3,
//                        -300,    -3,   outOfStock,                   0,   0,  -3,    outOfStock,            0,
//                           0,    -3,   outOfStock,                   0,   0,  -3,    outOfStock,            0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -50,   400,   "",                            4, -100, 300,   "",                    3,
//                        -300,   -3,   outOfStock,                    0, 0, -3,       outOfStock,            0,
//                          0,    -3,   outOfStock,                    0,  0,   -3,    outOfStock,            0,
//                },
//
////       -----------------------------------------------28-30- 三个对的一起拿，其他两个单独拿----------------------------------------------------------------------------------------------------------
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,                   3, -100, 250,   wrongPlaceAndOutOfStock, 2,
//                        -250,    -3,   outOfStock,                   0,    0,  -3,   outOfStock,              0,
//                           0,    -3,   outOfStock,                   0,    0,  -3,   outOfStock,              0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,                   3, -250, 100,   outOfStock,         1,
//                        -100,    -3,   outOfStock,                   0,    0, -3,    outOfStock,         0,
//                           0,    -3,   outOfStock,                   0,    0, -3,    outOfStock,         0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -250,   200,   outOfStock,                   2, -100, 100,   outOfStock,         1,
//                        -100,    -3,   outOfStock,                   0,    0,  -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                   0,    0,  -3,   outOfStock,         0,
//                },
////       -----------------------------------------------31-32- 单独拿一个对的，其他一起拿----------------------------------------------------------------------------------------------------------
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -100,   350,   wrongPlace,                   3, -350, -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                   0,    0, -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                   0,    0, -3,   outOfStock,         0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -350,   100,   outOfStock,                   1, -100, -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                   0,    0, -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                   0,    0, -3,   outOfStock,         0,
//                },
//
////       -----------------------------------------------33-34- 单独拿一个对的，其他一起拿----------------------------------------------------------------------------------------------------------
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -400,   50,   wrongPlaceAndOutOfStock,       0, -50, -3,   outOfStock,         0,
//                           0,   -3,   outOfStock,                    0,   0, -3,   outOfStock,         0,
//                           0,   -3,   outOfStock,                    0,   0, -3,   outOfStock,         0,
//                },
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -50,   400,   "",                            4, -400, -3,   outOfStock,         0,
//                          0,    -3,   outOfStock,                    0,    0, -3,   outOfStock,         0,
//                          0,    -3,   outOfStock,                    0,    0, -3,   outOfStock,         0,
//                },
//
////    -------------------------------------35-五个全一起拿----------------------------------------------------------------------------------------------------------
//                new Object[]{100, 400, 4, 400,  50, 450, wrongPlace, 4,
//                        -450,   -3,   outOfStock,                    0, 0, -3,   outOfStock,         0,
//                           0,   -3,   outOfStock,                    0, 0, -3,   outOfStock,         0,
//                           0,   -3,   outOfStock,                    0, 0, -3,   outOfStock,         0,
//                },
//
////                3个正确的和1个错误的
//
////   -----------------------------------------1-4-4个全单独拿----------------------------------------------------------------------------------------------------------
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -50,    300,           "",                   3, -100, 200,   outOfStock,         2,
//                        -100,   100,   outOfStock,                   1, -100,  -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                   0,    0,  -3,   outOfStock,         0,
//                },
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -100,   250,   wrongPlaceAndOutOfStock,      2, -50, 200,    outOfStock,         2,
//                        -100,   100,   outOfStock,                   1, -100, -3,    outOfStock,         0,
//                           0,    -3,   outOfStock,                   0,  0,   -3,    outOfStock,         0,
//                },
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -100,   250,   wrongPlaceAndOutOfStock,      2, -100, 150,   wrongPlaceAndOutOfStock, 1,
//                         -50,   100,   outOfStock,                   1, -100, -3,    outOfStock,              0,
//                           0,    -3,   outOfStock,                   0,  0,   -3,    outOfStock,              0,
//                },
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -100,   250,   wrongPlaceAndOutOfStock,      2, -100, 150,   wrongPlaceAndOutOfStock, 1,
//                        -100,    50,   wrongPlaceAndOutOfStock,      0,  -50,  -3,   outOfStock,              0,
//                           0,    -3,   outOfStock,                   0,    0,  -3,   outOfStock,              0,
//                },
//
////   -----------------------------------------5-7-1对1错一起拿，其他两个对的单独拿----------------------------------------------------------------------------------------------------------
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -150,   200,   outOfStock,               2, -100, 100,   outOfStock,         1,
//                        -100,    -3,   outOfStock,               0,    0,  -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,               0,    0,  -3,   outOfStock,         0,
//                },
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -100,   250,   wrongPlaceAndOutOfStock,      2, -150, 100,   outOfStock,     1,
//                        -100,    -3,   outOfStock,                   0,    0,  -3,   outOfStock,     0,
//                           0,    -3,   outOfStock,                   0,    0,  -3,   outOfStock,     0,
//                },
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -100,   250,   wrongPlaceAndOutOfStock,      2, -100, 150,   wrongPlaceAndOutOfStock, 1,
//                        -150,    -3,   outOfStock,                   0,    0,  -3,   outOfStock,              0,
//                           0,    -3,   outOfStock,                   0,    0,  -3,   outOfStock,              0,
//                },
//
////   -----------------------------------------8-13----------2对的一起拿，其他1对1错单独拿----------------------------------------------------------------------------------------------------------
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -50,   300,   "",                            3, -100, 200,   outOfStock,         2,
//                        -200,   -3,   outOfStock,                    0,    0,  -3,   outOfStock,         0,
//                           0,   -3,   outOfStock,                    0,    0,  -3,   outOfStock,         0,
//                },
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -50,   300,   "",                            3, -200, 100,   outOfStock,         1,
//                        -100,   -3,   outOfStock,                    0,    0,  -3,   outOfStock,         0,
//                           0,   -3,   outOfStock,                    0,    0,  -3,   outOfStock,         0,
//                },
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -100,   250,   wrongPlaceAndOutOfStock,      2, -50, 200,   outOfStock,         2,
//                        -200,    -3,   outOfStock,                   0,   0,  -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                   0,   0,  -3,   outOfStock,         0,
//                },
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -100,   250,   wrongPlaceAndOutOfStock,      2, -200, 50,   wrongPlaceAndOutOfStock, 0,
//                         -50,    -3,   outOfStock,                   0,    0, -3,   outOfStock,              0,
//                           0,    -3,   outOfStock,                   0,    0, -3,   outOfStock,              0,
//                },
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -200,   150,   wrongPlaceAndOutOfStock,      1, -50, 100,   outOfStock,         1,
//                        -100,    -3,   outOfStock,                   0,   0,  -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                   0,   0,  -3,   outOfStock,         0,
//                },
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -200,   150,   wrongPlaceAndOutOfStock,      1, -100, 50,   wrongPlaceAndOutOfStock, 0,
//                         -50,    -3,   outOfStock,                   0,    0, -3,   outOfStock,              0,
//                           0,    -3,   outOfStock,                   0,    0, -3,   outOfStock,              0,
//                },
//
////     ------------------------------14-15----------3个对的一起拿，1错的单独拿----------------------------------------------------------------------------------------------------------
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -300,   50,   wrongPlaceAndOutOfStock,       0, -50, -3,   outOfStock,         0,
//                           0,   -3,   outOfStock,                    0,   0, -3,   outOfStock,         0,
//                           0,   -3,   outOfStock,                    0,   0, -3,   outOfStock,         0,
//                },
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -50,   300,   "",                            3, -300, -3,   outOfStock,         0,
//                          0,    -3,   outOfStock,                    0,    0, -3,   outOfStock,         0,
//                          0,    -3,   outOfStock,                    0,    0, -3,   outOfStock,         0,
//                },
//
////     ------------------------------16-17----------1个对的单独拿，其他一起拿----------------------------------------------------------------------------------------------------------
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -250,   100,   outOfStock,                   1, -100, -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                   0,    0, -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                   0,    0, -3,   outOfStock,         0,
//                },
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -100,   250,   wrongPlaceAndOutOfStock,      2, -250, -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                   0,    0, -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                   0,    0, -3,   outOfStock,         0,
//                },
//
////     ------------------------------18----------都一起拿----------------------------------------------------------------------------------------------------------
//
//                new Object[]{100, 300, 3, 300,  50, 350, wrongPlace, 3,
//                        -350,   -3,   outOfStock,                    0, 0, -3,   outOfStock,         0,
//                           0,   -3,   outOfStock,                    0, 0, -3,   outOfStock,         0,
//                           0,   -3,   outOfStock,                    0, 0, -3,   outOfStock,         0,
//                },
//
//
//// -----------------------------------2个对的，1个错的--------------共8个case----------------------------------------
//                new Object[]{100, 200, 2, 200,  50, 250, wrongPlaceAndOutOfStock, 2,
//                        -50,   200,   outOfStock,                                 2, -200, -3,   outOfStock,  0,
//                          0,    -3,   outOfStock,                                 0,    0, -3,   outOfStock,  0,
//                          0,    -3,   outOfStock,                                 0,    0, -3,   outOfStock,  0,
//                },
//                new Object[]{100, 200, 2, 200,  50, 250, wrongPlaceAndOutOfStock, 2,
//                        -150,   100,   outOfStock,                                1, -100, -3,   outOfStock,  0,
//                           0,    -3,   outOfStock,                                0,    0, -3,   outOfStock,  0,
//                           0,    -3,   outOfStock,                                0,    0, -3,   outOfStock,  0,
//                },
//                new Object[]{100, 200, 2, 200,  50, 250, wrongPlaceAndOutOfStock, 2,
//                        -200,   50,   wrongPlaceAndOutOfStock,                    0, -50, -3,   outOfStock,  0,
//                           0,   -3,   outOfStock,                                 0,   0, -3,   outOfStock,  0,
//                           0,   -3,   outOfStock,                                 0,   0, -3,   outOfStock,  0,
//                },
//                new Object[]{100, 200, 2, 200,  50, 250, wrongPlaceAndOutOfStock, 2,
//                        -100,   150,   wrongPlaceAndOutOfStock,                   1, -150, -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                                0,    0, -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                                0,    0, -3,   outOfStock,         0,
//                },
//                new Object[]{100, 200, 2, 200,  50, 250, wrongPlaceAndOutOfStock, 2,
//                        -100,   150,   wrongPlaceAndOutOfStock,                   1, -100, 50,   wrongPlaceAndOutOfStock, 0,
//                         -50,    -3,   outOfStock,                                0,    0, -3,   outOfStock,              0,
//                           0,    -3,   outOfStock,                                0,    0, -3,   outOfStock,              0,
//                },
//                new Object[]{100, 200, 2, 200,  50, 250, wrongPlaceAndOutOfStock, 2,
//                        -100,   150,   wrongPlaceAndOutOfStock,                   1, -50, 100,   outOfStock,         1,
//                        -100,    -3,   outOfStock,                                0,   0,  -3,   outOfStock,         0,
//                           0,    -3,   outOfStock,                                0,   0,  -3,   outOfStock,         0,
//                },
//                new Object[]{100, 200, 2, 200,  50, 250, wrongPlaceAndOutOfStock, 2,
//                        -50,   200,   outOfStock,                                 2, -100, 100,   outOfStock,        1,
//                        -100,   -3,   outOfStock,                                 0,    0,  -3,   outOfStock,        0,
//                           0,   -3,   outOfStock,                                 0,    0,  -3,   outOfStock,        0,
//                },
//                new Object[]{100, 200, 2, 200,  50, 250, wrongPlaceAndOutOfStock, 2,
//                        -250,   -3,   outOfStock,                                 0, 0, -3,   outOfStock,         0,
//                           0,   -3,   outOfStock,                                 0, 0, -3,   outOfStock,         0,
//                           0,   -3,   outOfStock,                                 0, 0, -3,   outOfStock,         0,
//                },
//
////---------------------------------------1对的，1错的-----------------------------------------------
//                new Object[]{100, 100, 1, 100,  50, 150, wrongPlaceAndOutOfStock, 1,
//                        -100,   50,   wrongPlaceAndOutOfStock,                    0, -50, -3,   outOfStock,       0,
//                           0,   -3,   outOfStock,                                 0,   0, -3,   outOfStock,       0,
//                           0,   -3,   outOfStock,                                 0,   0, -3,   outOfStock,       0,
//                },
//                new Object[]{100, 100, 1, 100,  50, 150, wrongPlaceAndOutOfStock, 1,
//                        -50,   100,   outOfStock,                                 1, -100, -3,   outOfStock,    0,
//                          0,    -3,   outOfStock,                                 0,    0, -3,   outOfStock,    0,
//                          0,    -3,   outOfStock,                                 0,    0, -3,   outOfStock,    0,
//                },
//                new Object[]{100, 100, 1, 100,  50, 150, wrongPlaceAndOutOfStock, 1,
//                        -150,   -3,   outOfStock,                                 0, 0, -3,   outOfStock,       0,
//                           0,   -3,   outOfStock,                                 0, 0, -3,   outOfStock,       0,
//                           0,   -3,   outOfStock,                                 0, 0, -3,   outOfStock,       0,
//                },


        };
        return objects;
    }
}

