#默认使用配置
spring:
  profiles:
    active: dev
#    active: test

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.haisheng.framework.model
  mapperLocations: classpath:mapper/*.xml


datasource:
  driver-class-name: com.mysql.jdbc.Driver
  # 使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource
  filters: stat
  maxActive: 20
  initialSize: 1
  maxWait: 60000
  minIdle: 1
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: select 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxOpenPreparedStatements: 20

#视图层控制
spring.mvc.view.prefix: /
spring.mvc.view.suffix: .html

---
#开发配置
spring:
  profiles: dev

#  datasource:
#    url: jdbc:mysql://10.20.124.229:3306/onepiece?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    username: 'onepieceqshow'
#    password: '!ptqacKNe34567'


---
#测试环境配置
spring:
  profiles: test

#  datasource:
#    url: jdbc:mysql://10.20.124.330:3306/onepiece?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    username: 'onepieceqshow'
#    password: '!ptqacKNe34567'


---
#生产环境配置
spring:
  profiles: pro

#  datasource:
#    url: jdbc:mysql://10.20.124.330:3306/onepiece?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    username: 'onepieceqshow'
#    password: '!ptqacKNe34567'