package com.haisheng.framework.testng.bigScreen.crm.wm.enumerator.config;

import lombok.Getter;

/**
 * 项目id
 *
 * @author wangmin
 * @date 2020/7/24 14:45
 */
public enum EnumChecklistConfId {

    DB_SERVICE_ID_EDGE_SERVICE(1),
    DB_SERVICE_ID_CUSTOMER_DATA_SERVICE(2),
    DB_SERVICE_ID_BODY_SERVICE(3),
    DB_SERVICE_ID_FACE_SERVICE(4),
    DB_SERVICE_ID_AD_SERVICE(5),
    DB_SERVICE_ID_SHELF_SERVICE(7),
    DB_SERVICE_ID_CONTROL_CENTER_SERVICE(8),
    DB_SERVICE_ID_MANAGEMENT_PLATFORM_SERVICE(9),
    DB_SERVICE_ID_YUEXIU_SALES_OFFICE_DAILY_SERVICE(10),
    DB_SERVICE_ID_OPERATION_CENTER(11),
    DB_SERVICE_ID_YUEXIU_SALES_OFFICE_ONLINE_SERVICE(12),
    DB_SERVICE_ID_MANAGEMENT_PLATFORM_ONLINE_SERVICE(13),
    DB_SERVICE_ID_FEIDAN_DAILY_SERVICE(14),
    DB_SERVICE_ID_FEIDAN_ONLINE_SERVICE(15),
    DB_SERVICE_ID_MAGIC_MIRROR_DAILY_SERVICE(16),
    DB_SERVICE_ID_MENJIN_ALGORITHM_DAILY_SERVICE(17),
    DB_SERVICE_ID_MENJIN_BE_DAILY_SERVICE(18),
    DB_SERVICE_ID_AI_LIVING_AREA_DAILY_SERVICE(19),
    DB_SERVICE_ID_AI_LIVING_AREA_ONLINE_SERVICE(20),
    /**
     * CRM_日常
     */
    DB_SERVICE_ID_CRM_DAILY_SERVICE(21),
    /**
     * CRM_线上
     */
    DB_SERVICE_ID_CRM_ONLINE_SERVICE(26),
    DB_SERVICE_ID_XUNDIAN_DAILY_SERVICE(23),
    DB_SERVICE_ID_MENDIAN_DAILY_SERVICE(24),
    DB_SERVICE_ID_MENDIAN_ONLINE_SERVICE(25);

    EnumChecklistConfId(int id) {
        this.id = id;
    }

    @Getter
    private final int id;
}
